[package]
name = "starknet_bridge"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.4"
openzeppelin = "0.20.0"
piltover = { git = "https://github.com/keep-starknet-strange/piltover", ref = "26424182cef3c81deae7a0d2e05c2c662ff803f4" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.40.0" }

[[target.starknet-contract]]
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = ["piltover::appchain::appchain"]

[tool.voyager]
TokenBridge = { path = "src/bridge/token_bridge.cairo" }

[scripts]
test = "snforge test"
