[package]
name = "starknet_bridge"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.4"
openzeppelin = "0.20.0"
piltover = { git = "https://github.com/byteZorvin/piltover", ref = "ffc582dd0f733f257e9eef2b31979350da0ce0d2" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.40.0" }

[[target.starknet-contract]]
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = ["piltover::appchain::appchain"]

[tool.voyager]
TokenBridge = { path = "src/bridge/token_bridge.cairo" }

[scripts]
test = "snforge test"
