[package]
name = "udc"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin_presets = "2.0.0"
starknet = "2.12.1"

[dev-dependencies]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["openzeppelin_presets::UniversalDeployer"]

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
