name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  check-starknet-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v4

      - name: Check starknet_bridge
        working-directory: ./starknet_bridge
        run: |
          asdf plugin add scarb
          asdf install
          scarb fmt --check
          scarb build
  
  check-udc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - name: Check udc
        working-directory: ./udc
        run: |
          asdf plugin add scarb
          asdf install
          scarb build
