name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  test-starknet-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with: 
          tool_versions: starknet_bridge/.tool-versions
      - name: Run tests for starknet_bridge
        working-directory: ./starknet_bridge
        run: snforge test
