name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  test-starknet-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v4
      - name: Run tests for starknet_bridge
        working-directory: ./starknet_bridge
        run: |
          asdf plugin add scarb starknet-foundry
          asdf install
          snforge test
