name: Deploy Starknet Bridge

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js and set up cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Bridge Deployment Script
        run: npx ts-node ./scripts/bridgeDeploy.ts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Clone Madara repository
        run: git clone https://github.com/madara-alliance/madara-cli.git
      - name: Build and cache Madara Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./madara-cli/deps/madara
          push: false
          load: true
          tags: madara-node:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
