name: Deploy Starknet Bridge

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodule Branch
        run: |
          cd starkgate-contracts
          git submodule update --init --recursive
          git --no-pager log -1 --pretty

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js and set up cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      # this builds `madara` at the branch `l3-support`
      - name: Clone Madara repository
        run: |
          git clone --depth=1 https://github.com/madara-alliance/madara.git

      - name: Create Docker network
        run: docker network create bridge-network

      - name: Run l2
        run: |
          docker run -d --name l2-node --network bridge-network -p 9944:9944 -p 9943:9943 \
            -v ./madara/configs/:/apps/configs/ ghcr.io/madara-alliance/madara:manual-62d8aa1\
            --base-path ./madara-l2-db \
            --rpc-external --rpc-admin --rpc-admin-external --rpc-cors "*" \
            --rpc-port 9944 --rpc-admin-port 9943 \
            --sequencer --chain-config-path /apps/configs/presets/devnet.yaml \
            --feeder-gateway-enable --gateway-enable --gateway-external --gateway-port 8844 \
            --no-l1-sync --strk-per-eth 10000 --no-charge-fee \
            --blob-gas-price 1 --l1-gas-price 1 2>&1 | tee -a ./madara_output_l2.log

      - name: Wait for server to be ready
        run: |
          timeout=180  # 3 minutes in seconds
          elapsed=0
          until [ "$(curl -fsSL http://localhost:9944/health)" = "OK" ] && echo "Health check passed"; do
            echo "Waiting for server to be ready..."
            sleep 2
            elapsed=$((elapsed + 2))
            if [ $elapsed -ge $timeout ]; then
              echo "Timeout: Server did not become ready within 3 minutes"
              exit 1
            fi
          done
          echo "Server is ready!"
      
      - name: Remove l2_deployer_address from devnet.yaml
        run: |
          yq -i 'del(.l2_deployer_address)' ./madara/bootstrapper/src/configs/devnet.json
  
      # TODO(mehul, hotfix): This is a temporary workaround for address issues during UDC deployment.
      # We are currently getting address mismatch problems; revisit this logic to fix it properly later.
      - name: Run Bootstrapper on L2
        run: |
          docker run -d --name bootstrapper-udc-l2 --network bridge-network \
            -v ./madara/bootstrapper/src/configs/:/apps/configs/ \
            -e ETH_RPC=http://l2-node:9944 \
            -e ETH_PRIVATE_KEY=0x077e56c6dc32d40a67f6f7e6625c8dc5e570abe49c0a24e9202e4ae906abcc07 \
            -e CONFIG_HASH_VERSION=StarknetOsConfig2 \
            -e ROLLUP_SEQ_URL=http://l2-node:9944 \
            -e ROLLUP_DECLARE_V0_SEQ_URL=http://l2-node:9943 \
            -e ROLLUP_PRIVATE_KEY=0xabcd \
            ghcr.io/madara-alliance/bootstrapper:nightly \
            --config /apps/configs/devnet.json --mode udc

          # Wait for container to finish
          EXIT_CODE=$(docker wait bootstrapper-udc-l2)

          # Show logs
          docker logs bootstrapper-udc-l2
          
          # Check exit status
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Bootstrapper container failed with exit code $EXIT_CODE"
            exit 1
          fi
          echo "Bootstrapper container completed successfully" 

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v4

      - name: Build Starkgate Contracts
        run: |
          cd starkgate-contracts
          git checkout dev-2.9.2
          cd ..
          bash ./scripts/shell/build.sh

      - name: Build bridge contracts
        working-directory: ./starknet_bridge
        run: |
          asdf plugin add scarb
          asdf install
          scarb build

      - name: Install tsx
        run: pnpm i -g tsx

      - name: Run Core Contract Deployment Script
        run: |
          tsx ./scripts/cli.ts --dump-path=./contracts.json deploy-core
          tsx ./scripts/cli.ts --dump-path=./contracts.json set-program-info --chain-id MADARA_DEVNET
          tsx ./scripts/cli.ts --dump-path=./contracts.json set-fact-registry

      - name: Update Core Contract Address
        run: |
          # Extract and print the core contract address from JSON
          CORE_CONTRACT=$(jq -r '.contracts.l2.appchain' ./contracts.json)
          echo "Extracted core contract address: $CORE_CONTRACT"

          # Check if the extracted value is null and fail if it is
          if [ "$CORE_CONTRACT" == "null" ] || [ -z "$CORE_CONTRACT" ]; then
            echo "Error: Core contract address is null or empty."
            exit 1
          fi

          # Update the YAML file with the contract address
          yq -i ".eth_core_contract_address = \"$CORE_CONTRACT\"" ./madara/configs/presets/devnet.yaml

          # Print the updated value for verification
          echo "Updated core contract address to: $(yq '.eth_core_contract_address' ./madara/configs/presets/devnet.yaml)"

      - name: Run l3
        run: |
          docker run -d --name l3-node --network bridge-network \
            -p 9955:9955 -p 9953:9953 -v ./madara/configs/:/apps/configs/ ghcr.io/madara-alliance/madara:manual-62d8aa1 \
            --base-path ./madara-l3-db \
            --rpc-cors "*" --rpc-external --rpc-admin --rpc-admin-external \
            --rpc-port 9955 --rpc-admin-port 9953 \
            --sequencer --chain-config-path /apps/configs/presets/devnet.yaml \
            --feeder-gateway-enable --gateway-enable --gateway-external --gateway-port 8080 \
            --settlement-layer STARKNET \
            --l1-endpoint http://l2-node:9944 \
            --strk-per-eth 10000 --no-charge-fee \
            --blob-gas-price 0 --l1-gas-price 0 2>&1 | tee -a ./madara_output_l3.log

      - name: Wait for server to be ready
        run: |
          timeout=180  # 3 minutes in seconds
          elapsed=0
          until [ "$(curl -fsSL http://localhost:9955/health)" = "OK" ] && echo "Health check passed"; do
            echo "Waiting for server to be ready..."
              sleep 2
              elapsed=$((elapsed + 2))
              if [ $elapsed -ge $timeout ]; then
                echo "Timeout: Server did not become ready within 3 minutes"
                exit 1
              fi
          done
          echo "Server is ready!"

      - name: Remove l2_deployer_address from devnet.yaml
        run: |
          yq -i 'del(.l2_deployer_address)' ./madara/bootstrapper/src/configs/devnet.json

      - name: Run Bootstrapper on L3
        run: |
          docker run -d --name bootstrapper-udc-l3 --network bridge-network \
            -v ./madara/bootstrapper/src/configs/:/apps/configs/ \
            -e ETH_RPC=http://l2-node:9944 \
            -e ETH_PRIVATE_KEY=0x077e56c6dc32d40a67f6f7e6625c8dc5e570abe49c0a24e9202e4ae906abcc07 \
            -e CONFIG_HASH_VERSION=StarknetOsConfig2 \
            -e ROLLUP_SEQ_URL=http://l3-node:9955 \
            -e ROLLUP_DECLARE_V0_SEQ_URL=http://l3-node:9953 \
            -e ROLLUP_PRIVATE_KEY=0xabcd \
            ghcr.io/madara-alliance/bootstrapper:nightly \
            --config /apps/configs/devnet.json --mode udc

          # Wait for container to finish
          EXIT_CODE=$(docker wait bootstrapper-udc-l3)

          # Show logs
          docker logs bootstrapper-udc-l3
          
          # Check exit status
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Bootstrapper container failed with exit code $EXIT_CODE"
            exit 1
          fi
          echo "Bootstrapper container completed successfully" 

      - name: Run Bridge Deployment Script
        run: |
          tsx ./scripts/cli.ts --dump-path=./contracts.json full-flow
          tsx ./scripts/cli.ts --dump-path=./contracts.json deploy-erc20

      - name: Run Token Actions
        run: |
          tsx ./scripts/cli.ts --dump-path=./contracts.json token-actions --token=ERC20_OZ

      - name: Run Role Transfer Script
        run: |
          tsx ./scripts/cli.ts --dump-path=./contracts.json transfer-roles

      - name: Check if all roles granted
        run: tsx ./scripts/cli.ts --dump-path=./contracts.json check-roles

      - name: Renounce roles
        run: tsx ./scripts/cli.ts --dump-path=./contracts.json renounce-roles
